#!/usr/bin/perl

#### Ana Rodriguez Sanchez-Archidona, Luxembourg 27/7/2013, Luxembourg Center for Systems Biomedicine ####
#### Modul that includes different gene regulatory raw network and experimental gene expression data examples

use strict;
use warnings;

package  Examples;

#Example network and experimental data 1
sub example1{
	my @network_example = (
		'SNAI1 -> ZEB1',
		'SNAI1 -> ZEB2',
		'SNAI1 -| CDH1',
		'SNAI1 -| MIR-200',
		'SNAI1 -| MIR-203',
		'ZEB1 -| CDH1',
		'ZEB1 -| MIR-200',
		'ZEB1 -| MIR-203',
		'ZEB2 -| CDH1',
		'ZEB2 -| MIR-200',
		'ZEB2 -| MIR-203',
		'MIR-200 -| ZEB1',
		'MIR-200 -| ZEB2',
		'MIR-203 -| SNAI1',
		'MIR-203 -| ZEB2');
        
	my @phenotype = (
		"CDH1 DOWN\n",
		"MIR-200 DOWN\n",
		"MIR-203 DOWN\n",
		"SNAI1 UP\n",
		"ZEB1 UP\n",
		"ZEB2 UP\n");
	
    return (\@network_example,\@phenotype);
}

#Example network and experimental data 2
sub example2{
	my @network_example = (
		'FOXP3 -> FOXP3',
		'FOXP3 -| GATA3',
		'FOXP3 -| RORGT',
		'FOXP3 -| TBET',
		'GATA3 -> GATA3',
		'GATA3 -> IL10',
		'GATA3 -> IL4',
		'GATA3 -| RORGT',
		'GATA3 -| STAT4',
		'GATA3 -| TBET',
		'IFNB -> IFNBR',
		'IFNBR -> STAT1',
		'IFNG -> IFNGR',
		'IFNGR -> JAK1',
		'IL10 -> IL10R',
		'IL10R -> STAT3',
		'IL12 -> IL12R',
		'IL12R -> STAT4',
		'IL18 -> IL18R',
		'IL18R -> IRAK',
		'IL2 -> IL2R',
		'IL23 -> IL23R',
		'IL23R -> STAT3',
		'IL2R -> STAT5',
		'IL4 -> IL4R',
		'IL4R -> STAT6',
		'IL6 -> IL6R',
		'IL6R -> JAK3',
		'IRAK -> IFNG',
		'JAK1 -> STAT1',
		'JAK3 -> RORGT',
		'NFAT -> IFNG',
		'RORGT -> IL17',
		'RORGT -> IL6',
		'RORGT -> RORGT',
		'RORGT -| FOXP3',
		'RORGT -| GATA3',
		'RORGT -| TBET',
		'SOCS1 -| IL4R',
		'SOCS1 -| JAK1',
		'STAT1 -> SOCS1',
		'STAT1 -> TBET',
		'STAT1 -| IL4',
		'STAT3 -> RORGT',
		'STAT3 -| IFNG',
		'STAT4 -> IFNG',
		'STAT5 -> FOXP3',
		'STAT6 -> GATA3',
		'STAT6 -| IL12R',
		'STAT6 -| IL18R',
		'TBET -> IFNG',
		'TBET -> SOCS1',
		'TBET -> TBET',
		'TBET -| FOXP3',
		'TBET -| GATA3',
		'TBET -| RORGT',
		'TCR -> NFAT',
		'TGFB -> FOXP3',
		'TGFB -> TGFBR',
		'TGFBR -> RORGT');

	my @phenotype = (
		"FOXP3 DOWN\n",
		"GATA3 UP\n",
		"IFNB DOWN\n",
		"IFNBR DOWN\n",
		"IFNG DOWN\n",
		"IFNGR DOWN\n",
		"IL10 UP\n",
		"IL10R UP\n",
		"IL12 DOWN\n",
		"IL12R DOWN\n",
		"IL17 DOWN\n",
		"IL18 DOWN\n",
		"IL18R DOWN\n",
		"IL2 DOWN\n",
		"IL23 DOWN\n",
		"IL23R DOWN\n",
		"IL2R DOWN\n",
		"IL4 UP\n",
		"IL4R UP\n",
		"IL6 DOWN\n",
		"IL6R DOWN\n",
		"IRAK DOWN\n",
		"JAK1 DOWN\n",
		"JAK3 DOWN\n",
		"NFAT DOWN\n",
		"RORGT DOWN\n",
		"SOCS1 DOWN\n",
		"STAT1 DOWN\n",
		"STAT3 UP\n",
		"STAT4 DOWN\n",
		"STAT5 DOWN\n",
		"STAT6 UP\n",
		"TBET DOWN\n",
		"TCR DOWN\n",
		"TGFB DOWN\n",
		"TGFBR DOWN\n");
	
    return (\@network_example,\@phenotype);
}

#Example network and experimental data 3
sub example3{
	my @network_example = (
		'BMP2K -> BMP2',
		'CAMP -> CGA',
		'CAMP -> CGB',
		'CAMP -| LMCD1',
		'CDX2 -> CDX2',
		'CDX2 -| POU5F1',
		'CEBPA -> SP1',
		'CTNNB1 -> HNF4A',
		'CTNNB1 -> LEF1-CTNNB1',
		'E2F4 -> FOXD3',
		'E2F4 -> MYC',
		'E2F4 -> NFYA',
		'E2F4 -> PIAS1',
		'E2F4 -> SP1',
		'E2F4 -> SUMO1',
		'E2F4 -> TCF3',
		'E2F4 -| CEBPA',
		'E2F4 -| T',
		'FOXA1 -> AFP',
		'FOXA1 -> FOXA1',
		'FOXA2 -> AFP',
		'FOXA2 -> FOXA2',
		'FOXD3 -> FOXA1',
		'FOXD3 -> FOXA2',
		'FOXD3 -> POU5F1-FOXD3',
		'GATA2 -> CGA',
		'GATA3 -> CGA',
		'GATA4 -| GATA6',
		'GATA6 -> GATA6',
		'GATA6 -> HNF4A',
		'GATA6 -| NANOG',
		'HNF4A -> BMP2K',
		'KLF4 -> NANOG',
		'LEF1 -> LEF1-CTNNB1',
		'LEF1 -> SALL4',
		'LEF1-CTNNB1 -> MYC',
		'LMCD1 -| GATA6',
		'MAD -> MAD-MAX',
		'MAX -> MAD-MAX',
		'MAX -> MYC-MAX',
		'MYC -> MYC-MAX',
		'MYC -> MYC-SP1',
		'MYC-SP1 -| SP1',
		'NANOG -> FOXD3',
		'NANOG -> FOXO1A',
		'NANOG -> GDF3',
		'NANOG -> KLF4',
		'NANOG -> LMCD1',
		'NANOG -> NANOG',
		'NANOG -> PBX1',
		'NANOG -> POU5F1',
		'NANOG -> PRDM14',
		'NANOG -> SALL4',
		'NANOG -> SOX2',
		'NANOG -> SUMO1',
		'NANOG -> TDGF1',
		'NANOG -> ZFP42',
		'NANOG -> ZIC3',
		'NANOG -> ZNF206',
		'NANOG -| BMP2',
		'NANOG -| CDX2',
		'NANOG -| GATA2',
		'NANOG -| GATA3',
		'NANOG -| GATA4',
		'NANOG -| GATA6',
		'NANOG -| LEF1',
		'NANOG -| T',
		'NFYA -> SP1',
		'PBX1 -> NANOG',
		'PIAS1 -> GATA4',
		'PIAS1 -> PIAS1',
		'PIAS1 -> PIASY',
		'PIAS1 -| SP3',
		'PIASY -| GATA2',
		'POU5F1 -> FOXD3',
		'POU5F1 -> FOXO1A',
		'POU5F1 -> KLF4',
		'POU5F1 -> POU5F1-FOXD3',
		'POU5F1 -> POU5F1-SOX2',
		'POU5F1 -> PRDM14',
		'POU5F1 -> TDGF1',
		'POU5F1 -> ZFP42',
		'POU5F1 -| CDX2',
		'POU5F1 -| CGA',
		'POU5F1 -| CGB',
		'POU5F1 -| GATA4',
		'POU5F1 -| GATA6',
		'POU5F1 -| LEF1',
		'POU5F1 -| SOX17',
		'POU5F1 -| T',
		'POU5F1-FOXD3 -| FOXA1',
		'POU5F1-FOXD3 -| FOXA2',
		'POU5F1-SOX2 -> NANOG',
		'POU5F1-SOX2 -> POU5F1',
		'POU5F1-SOX2 -> SOX2',
		'PRDM14 -> MYC',
		'PRDM14 -| CSH1',
		'PRDM14 -| GATA6',
		'PRDM14 -| T',
		'SOX17 -> FOXA2',
		'SOX2 -> FOXD3',
		'SOX2 -> FOXO1A',
		'SOX2 -> KLF4',
		'SOX2 -> NFYA',
		'SOX2 -> POU5F1-SOX2',
		'SOX2 -> PRDM14',
		'SOX2 -> SALL4',
		'SOX2 -> TDGF1',
		'SOX2 -> ZIC3',
		'SOX2 -| BMP2',
		'SOX2 -| GATA2',
		'SP1 -> CGB',
		'SP1 -> MYC-SP1',
		'SP1 -> SP1',
		'SP1 -| CEBPA',
		'SP3 -> CGB',
		'SP3 -| SP1',
		'SUMO1 -> GATA4',
		'SUMO1 -| GATA2',
		'SUMO1 -| SP3',
		'TCF3 -| MYC',
		'ZIC3 -> NANOG',
		'ZIC3 -| SOX17');

	my @phenotype = (
		"AFP DOWN\n",
		"BMP2 DOWN\n",
		"BMP2K DOWN\n",
		"CAMP DOWN\n",
		"CDX2 DOWN\n",
		"CEBPA UP\n",
		"CGA DOWN\n",
		"CGB DOWN\n",
		"CSH1 DOWN\n",
		"CTNNB1 DOWN\n",
		"E2F4 DOWN\n",
		"FOXA1 DOWN\n",
		"FOXA2 DOWN\n",
		"FOXD3 UP\n",
		"FOXO1A UP\n",
		"GATA2 DOWN\n",
		"GATA3 DOWN\n",
		"GATA4 DOWN\n",
		"GATA6 DOWN\n",
		"GDF3 UP\n",
		"HNF4A DOWN\n",
		"KLF4 UP\n",
		"LEF1 DOWN\n",
		"LEF1_CTNNB1 DOWN\n",
		"LMCD1 UP\n",
		"MAD DOWN\n",
		"MAD_MAX DOWN\n",
		"MAX DOWN\n",
		"MYC UP\n",
		"MYC_MAX UP\n",
		"MYC_SP1 UP\n",
		"NANOG UP\n",
		"NFYA UP\n",
		"PBX1 UP\n",
		"PIAS1 UP\n",
		"PIASY UP\n",
		"POU5F1 UP\n",
		"POU5F1_FOXD3 UP\n",
		"POU5F1_SOX2 UP\n",
		"PRDM14 UP\n",
		"SALL4 UP\n",
		"SOX17 DOWN\n",
		"SOX2 UP\n",
		"SP1 DOWN\n",
		"SP3 DOWN\n",
		"SUMO1 UP\n",
		"T DOWN\n",
		"TCF3 DOWN\n",
		"TDGF1 UP\n",
		"ZFP42 UP\n",
		"ZIC3 UP\n",
		"ZNF206 UP\n");
	
    return (\@network_example,\@phenotype);
}
1
